<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MultiCut\MultiCutShortcut\MultiCutShortcut.csproj" />
  </ItemGroup>

</Project>
